#!/bin/bash
echo "Running pre build scripts"
export JAVA_HOME=/etc/alternatives/java_sdk_1.8.0
# export PATH=$JAVA_HOME/bin:$PATH
export M2_HOME=$OPENSHIFT_DATA_DIR/apache-maven-3.3.3
export PATH=/etc/alternatives/java_sdk_1.8.0/bin:$OPENSHIFT_DATA_DIR/apache-maven-3.3.3/bin:/opt/rh/mongodb24/root/usr/bin:/bin:/usr/bin:/usr/sbin

java -version